#include <iostream>
using namespace std;

class CompleteBT {
    int* tree;
    int capacity;
    int filledSize;

public:
    CompleteBT(int size) : tree(new int[size]{}), capacity(size), filledSize(0) {}

    void insert(int data) {
        if(filledSize == capacity) {
            cout << "Complete BT has been filled completely...!\n";
            return;
        }

        tree[filledSize++] = data;
    }

    void deleteLast() {
        if(filledSize == 0) {
            cout << "Complete BT is already emty...!\n";
            return;
        }

        filledSize--;
    }

    void del(int index) {
        if(filledSize == 0) {
            cout << "Complete BT is already empty...!\n";
            return;
        }

        if(index < 0 || index >= filledSize) {
            cout << "Invalid Index...!\n";
            return;
        }

        swap(tree[index], tree[--filledSize]);
    }

    // print() -- Generated by AI
    void print() {
        if (filledSize == 0) {
            cout << "Complete BT is empty...!\n";
            return;
        }

        int totalLevels = 0;
        int temp = filledSize;
        while (temp > 0) {
            totalLevels++;
            temp = (temp - 1) / 2;
        }
        
        // Calculate actual number of levels
        int levels = 0;
        int nodes = filledSize;
        int levelNodes = 1;
        while (nodes > 0) {
            levels++;
            nodes -= levelNodes;
            levelNodes *= 2;
        }

        int currentLevelStartIndex = 0;
        int nodesInCurrentLevel = 1;
        int level = 0;
        int maxWidth = (1 << levels) * 3; // Width for spacing

        cout << "\n";
        while (currentLevelStartIndex < filledSize) {
            int spacing = maxWidth / (nodesInCurrentLevel + 1);
            
            // Print leading spaces
            cout << string(spacing / 2, ' ');
            
            int nodesPrintedThisLevel = 0;
            for (int i = currentLevelStartIndex; i < filledSize && nodesPrintedThisLevel < nodesInCurrentLevel; ++i) {
                cout << tree[i];
                if (nodesPrintedThisLevel < nodesInCurrentLevel - 1 && i + 1 < filledSize) {
                    cout << string(spacing, ' ');
                }
                nodesPrintedThisLevel++;
            }
            cout << "\n";

            currentLevelStartIndex += nodesInCurrentLevel;
            nodesInCurrentLevel *= 2;
            level++;
        }
        cout << "\n";
    }
};

int main() {
    
    CompleteBT bt(5);

    bt.insert(34);
    bt.insert(65);
    bt.insert(2);
    bt.insert(4);
    bt.insert(99);
    bt.print();

    bt.deleteLast();
    bt.print();

    bt.del(0);
    bt.print();
    
    return 0;
}
